### ISSUE TITLE
Add section layout preview images

### ISSUE THREAD

**Issue by jrbeeman** [balsama/engage-demo#15] opened 2018-10-19 18:30 UTC
Currently the "Choose a layout" form has missing images for most layout options.

![image](https://user-images.githubusercontent.com/211558/47236920-68b24680-d392-11e8-9689-78b9c15ed14a.png)

**Comment by balsama** [comment] 2018-10-23 12:31
@phenaproxima / @timplunkett Do you have any ideas about what could cause this? These layouts are provided by Lightning Layout. Not reproducible on a standard install of Lightning Layout, but I'm not sure where to start looking.

**Comment by phenaproxima** [comment] 2018-10-23 13:39
This is quite puzzling.

One thing I know (off the top of my head) is that the icons are dynamically generated SVGs. Is it possible that an error occurred while trying to generate those (presumably they are written out the file system)? Maybe checking the watchdog logs is a good place to start...

**Comment by balsama** [comment] 2018-10-23 14:27
Ah. Looks like this is LB and Panels not playing nicely together. Disabling panels fixes the problem.

That would be enough except we use Moderation Dashboard in the demo and Moderation Dashboard uses Panels 😬

**Comment by phenaproxima** [comment] 2018-10-23 14:44
It's definitely Panels. It implements hook_layout_alter, which is specifically and deliberately interfering with the icons.

My suggestion is to disable the hook. You can use hook_module_implements_alter for that:

```php
function engage_demo_module_implements_alter(array &$implementations, $hook) {
  if ($hook === 'layout_alter') {
    unset($implementations['panels']);
  }
}
```
Clear all caches after implementing that in a module, and it should be fixed. I tried replacing the hook with an instant return, and it fixed the problem for me (which I was reproducing on a clean install of Lightning 8.x-4.x.).

**Closed as completed** 2018-10-23 15:26 UTC

**Comment by balsama** [comment] 2018-10-23 15:34
Implemented and fixed. Thanks @phenaproxima !
